# Background and foreground colors
background = #1a1a28
foreground = #b5c3ef

# Standard colors
palette = 0=#1a1a28
palette = 1=#ef638a
palette = 2=#86d97f
palette = 3=#f6d58a
palette = 4=#609af8
palette = 5=#b682f4
palette = 6=#70d8c7
palette = 7=#b5c3ef

# Bright colors
palette = 8=#3a3c4c
palette = 9=#ef638a
palette = 10=#86d97f
palette = 11=#f6d58a
palette = 12=#609af8
palette = 13=#b682f4
palette = 14=#70d8c7
palette = 15=#ffffff
