background            #1a1a28
foreground            #b5c3ef

# black
color0  #1a1a28
color8  #3a3c4c

# red
color1  #ef638a
color9  #ef638a

# green
color2  #86d97f
color10 #86d97f

# yellow
color3  #f6d58a
color11 #f6d58a

# blue
color4  #609af8
color12 #609af8

# magenta
color5  #b682f4
color13 #b682f4

#cyan
color6  #70d8c7
color14 #70d8c7

#white
color7  #b5c3ef
color15 #ffffff


